const List1 = [["Zero", "0"], ["Reciprocal of Croutonplex (ill-defined)", "<sup>1</sup>&frasl;<sub>Croutonplex</sub>"], ["2 divided by Croutonplex (ill-defined)", "<sup>2</sup>&frasl;<sub>Croutonplex</sub>"], ["Croutonillionth (ill-defined)", "<sup>1</sup>&frasl;<sub>Croutonillion</sub>"],
               ["2 divided by Croutonillion (ill-defined)", "<sup>2</sup>&frasl;<sub>Croutonillion</sub>"], ["10 divided by Croutonillion (ill-defined)", "<sup>10</sup>&frasl;<sub>Croutonillion</sub>"], ["100 divided by Croutonillion (ill-defined)", "<sup>100</sup>&frasl;<sub>Croutonillion</sub>"],
               ["1000 divided by Croutonillion (ill-defined)", "<sup>1000</sup>&frasl;<sub>Croutonillion</sub>"], ["1000000 divided by Croutonillion (ill-defined)", "<sup>1000000</sup>&frasl;<sub>Croutonillion</sub>"], ["10<sup>10</sup> divided by Croutonillion (ill-defined)", "<sup>10<sup>10</sup></sup>&frasl;<sub>Croutonillion</sub>"],
               ["Googol divided by Croutonillion (ill-defined)", "<sup>10<sup>100</sup></sup>&frasl;<sub>Croutonillion</sub>"], ["Trialogue divided by Croutonillion (ill-defined)", "<sup>10<sup>10<sup>10</sup></sup></sup>&frasl;<sub>Croutonillion</sub>"], ["Googolplex divided by Croutonillion (ill-defined)", "<sup>10<sup>10<sup>100</sup></sup></sup>&frasl;<sub>Croutonillion</sub>"],
               ["Decker divided by Croutonillion (ill-defined)", "<sup>10&uarr;&uarr;10</sup>&frasl;<sub>Croutonillion</sub>"], ["Giggol divided by Croutonillion (ill-defined)", "<sup>10&uarr;&uarr;100</sup>&frasl;<sub>Croutonillion</sub>"], ["Deka-taxis divided by Croutonillion (ill-defined)", "<sup>10&uarr;&uarr;&uarr;10</sup>&frasl;<sub>Croutonillion</sub>"],
               ["Tridecal divided by Croutonillion (ill-defined)", "<sup>10&uarr;<sup>10</sup>10</sup>&frasl;<sub>Croutonillion</sub>"], ["Graham's Number divided by Croutonillion (ill-defined)", "<sup>G64</sup>&frasl;<sub>Croutonillion</sub>"], ["Iteral divided by Croutonillion (ill-defined)", "<sup>{10, 10 (1) 2}</sup>&frasl;<sub>Croutonillion</sub>"],
               ["TREE(3) divided by Croutonillion (ill-defined)", "<sup>TREE(3)</sup>&frasl;<sub>Croutonillion</sub>"], ["SSCG(3) divided by Croutonillion (ill-defined)", "<sup>SSCG(3)</sup>&frasl;<sub>Croutonillion</sub>"], ["Dekulus divided by Croutonillion (ill-defined)", "<sup>{10, 10 / 2}</sup>&frasl;<sub>Croutonillion</sub>"], 
               ["SCG(13) divided by Croutonillion (ill-defined)", "<sup>SCG(13)</sup>&frasl;<sub>Croutonillion</sub>"], ["Loader\'s Number divided by Croutonillion (ill-defined)", "<sup>D<sup>5</sup>(99)</sup>&frasl;<sub>Croutonillion</sub>"], ["S(643) divided by Croutonillion (ill-defined)", "<sup>S(643)</sup>&frasl;<sub>Croutonillion</sub>"], 
               ["Σ(745) divided by Croutonillion (ill-defined)", "<sup>Σ(745)</sup>&frasl;<sub>Croutonillion</sub>"], ["Σ(1919) divided by Croutonillion (ill-defined)", "<sup>Σ(1919)</sup>&frasl;<sub>Croutonillion</sub>"], ["Ξ(1000000) divided by Croutonillion (ill-defined)", "<sup>Ξ(1000000)</sup>&frasl;<sub>Croutonillion</sub>"], 
               ["Rayo\'s Number divided by Croutonillion (ill-defined)", "<sup>Rayo(10<sup>100</sup>)</sup>&frasl;<sub>Croutonillion</sub>"], ["BIG FOOT divided by Croutonillion (ill-defined)", "<sup>FOOT<sup>10</sup>(10<sup>100</sup>)</sup>&frasl;<sub>Croutonillion</sub>"], ["Little Bigeddon divided by Croutonillion (ill-defined)", "<sup>Em(12&uarr;&uarr;12)</sup>&frasl;<sub>Croutonillion</sub>"],
               ["Big Bigeddon (Sasquatch) divided by Croutonillion (ill-defined)", "<sup>Em<sub>2</sub>(12&uarr;&uarr;12)</sup>&frasl;<sub>Croutonillion</sub>"], ["Large Number Garden Number divided by Croutonillion (ill-defined)", "<sup>LNGN<sup>10</sup>(10&uarr;<sup>10</sup>10)</sup>&frasl;<sub>Croutonillion</sub>"], ["Hollom\'s Number divided by Croutonillion (ill-defined)", "<sup>Ι<sub>6.985&times;10<sup>104</sup></sub>(200)</sup>&frasl;<sub>Croutonillion</sub>"],
               ["Oblivion divided by Croutonillion (ill-defined)", "<sup>Oblivion</sup>&frasl;<sub>Croutonillion</sub>"], ["Utter Oblivion divided by Croutonillion (ill-defined)", "<sup>Utter Oblivion</sup>&frasl;<sub>Croutonillion</sub>"], ["Ultimate Oblivion divided by Croutonillion (ill-defined)", "<sup>Ultimate Oblivion</sup>&frasl;<sub>Croutonillion</sub>"],
               ["Sam\'s Number divided by Croutonillion (ill-defined)", "<sup>Sam\'s Number</sup>&frasl;<sub>Croutonillion</sub>"], ["Crouton divided by Croutonillion (ill-defined)", "<sup>Crouton</sup>&frasl;<sub>Croutonillion</sub>"], ["Croutonth (ill-defined)", "<sup>1</sup>&frasl;<sub>Crouton</sub>"], 
               ["2 divided by Crouton (ill-defined)", "<sup>2</sup>&frasl;<sub>Crouton</sub>"], ["Sam\'s Number divided by Crouton (ill-defined)", "<sup>Sam\'s Number</sup>&frasl;<sub>Crouton</sub>"], ["Reciprocal of Sam\'s Number (ill-defined)", "<sup>1</sup>&frasl;<sub>Sam\'s Number</sub>"],
               ["2 divided by Sam\'s Number (ill-defined)", "<sup>2</sup>&frasl;<sub>Sam\'s Number<sub>"], ["Destructive and Powerful Mitskiillion (I\'m not joking, this is the name) divided by Sam\'s Number (ill-defined)", "<sup>Destructive and Powerful Mitskiillion</sup>&frasl;<sub>Sam\'s Number</sub>"], ["Destructive and Powerful Mitskiillionth (I\'m not joking, this is the name) (ill-defined)", "<sup>1</sup>&frasl;<sub>Destructive and Powerful Mitskiillion</sub>"],
               ["2 divided by Destructive and Powerful Mitskiillion (ill-defined)", "<sup>2</sup>&frasl;<sub>Destructive and Powerful Mitskiillion</sub>"], ["Powerful Mitskiillion (I\'m not joking, this is the name) divided by Destructive and Powerful Mitskiillion (ill-defined)", "<sup>Powerful Mitskiillion</sup>&frasl;<sub>Destructive and Powerful Mitskiillion</sub>"], ["Powerful Mitskiillionth (I\'m not joking, this is the name) (ill-defined)", "<sup>1</sup>&frasl;<sub>Powerful Mitskiillion</sub>"]];
var x = 0;
for(x = 0; x < List1.length; x++) {
   document.body.innerHTML += '<p id=`Number${x}`>'+(x+1).toString()+'. '+List1[x][0].toString()+', '+List1[x][1].toString()+'</p>';
}
